yatube/about/urls.py
from django.urls import path
from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path("posts/<int:post_id>/edit/", views.post_edit, name="post_edit"),
    path('create/', views.post_create, name='post_create'),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/users/urls.py
from django.contrib.auth.views import (LoginView, LogoutView,
                                       PasswordChangeDoneView,
                                       PasswordChangeView,
                                       PasswordResetCompleteView,
                                       PasswordResetConfirmView,
                                       PasswordResetDoneView,
                                       PasswordResetView)
from django.urls import path, reverse_lazy

from . import views

app_name = 'users'

urlpatterns = [
    path('signup/',
         views.SignUp.as_view(template_name='users/signup.html'),
         name='signup'
         ),
    path('logout/',
         LogoutView.as_view(template_name='users/logged_out.html'),
         name='logout'
         ),
    path('login/',
         LoginView.as_view(template_name='users/login.html'),
         name='login'
         ),
    path('password_change/done/',
         PasswordChangeDoneView.as_view(
             template_name='users/password_change_done.html'),
         name='password_change_done'
         ),
    path('password_change/',
         PasswordChangeView.as_view(
             template_name='users/password_change_form.html',
             success_url=reverse_lazy('users:password_change_done')),
         name='password_change',
         ),
    path('password_reset/done/',
         PasswordResetDoneView.as_view(
             template_name='users/password_reset_done.html'),
         name='password_reset_done'
         ),
    path('password_reset/',
         PasswordResetView.as_view(
             template_name='users/password_reset_form.html'),
         name='password_reset'
         ),
    path('reset/done/',
         PasswordResetCompleteView.as_view(
             template_name='users/password_reset_complete.html'),
         name='password_reset_complite'
         ),
    path('reset/<str:uidb64>/<str:token>/',
         PasswordResetConfirmView.as_view(
             template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm'
         )
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

FIRST_SYMBOLS: int = 15

User = get_user_model()


class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts'
    )
    group = models.ForeignKey('Group', blank=True, null=True,
                              on_delete=models.SET_NULL, related_name='posts')
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ['-pub_date']

    def __str__(self) -> str:
        return self.text[:FIRST_SYMBOLS]


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self) -> str:
        return self.title

yatube/posts/forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('text', 'group',)

yatube/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model


User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

yatube/about/views.py
from django.views.generic.base import TemplateView


class AboutAuthorView(TemplateView):
    template_name = 'about/author.html'


class AboutTechView(TemplateView):
    template_name = 'about/tech.html'

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator

from .models import Post, Group, User
from .forms import PostForm


POSTS_IN_PAGE: int = 10
TITTLE: int = 30


def index(request):
    post_list = Post.objects.all()
    paginator = Paginator(post_list, POSTS_IN_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()
    paginator = Paginator(posts, POSTS_IN_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'group': group,
        'page_obj': page_obj
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    posts = author.posts.all()
    count = author.posts.count()
    paginator = Paginator(posts, POSTS_IN_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'count': count,
        'author': author,
        'page_obj': page_obj,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    pub_date = post.pub_date
    post_title = post.text[:TITTLE]
    author = post.author
    author_posts = author.posts.all().count()
    context = {
        'post': post,
        'post_title': post_title,
        'pub_date': pub_date,
        'author': author,
        'author_posts': author_posts,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required(login_url="users:login")
def post_create(request):
    """Добавления поста."""

    template = "posts/post_create.html"

    form = PostForm(request.POST or None)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.author = request.user
        instance.save()
        return redirect("posts:profile", request.user)

    return render(request, template, {"form": form})


@login_required(login_url="users:login")
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if post.author != request.user:
        return redirect('posts:post_detail', post_id=post_id)

    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id=post_id)
    context = {
        'post': post,
        'form': form,
        'is_edit': True,
    }
    return render(request, 'posts/post_create.html', context)

yatube/users/views.py
from django.views.generic import CreateView
from django.urls import reverse_lazy

from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('posts:index')
    template_name = 'users/signup.html'

yatube/templates/about/author.html
{% extends "base.html" %}
{% block title %}Об авторе проекта{% endblock %}
{% block content %}
<h1>Привет, я автор</h1>
<p>
  Меня зовут Кирилл, я обучаюсь в Яндекс практикуме и мне это нравится. Считаю, что данный курс поможет мне устроиться на работу. 
</p>
{% endblock %}

yatube/templates/about/tech.html
{% extends "base.html" %}
{% block title %}Технологии{% endblock %}
{% block content %}
<div class="row">
  <h1>Вот что я умею</h1>
  <aside class="col-12 col-md-3">
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        Python
      </li>
      <li class="list-group-item">
        Django
      </li>
    </ul>
  </aside>
  <article class="col-12 col-md-9">
    <p>Текст страницы "Технологии"</p>
  </article>
</div>
{% endblock %} 

yatube/templates/base.html
{% load static %}
<!DOCTYPE html> <!-- Используется html 5 версии -->
<html lang="ru"> <!-- Язык сайта - русский -->
  <head> 
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <meta charset="utf-8"> <!-- Кодировка сайта -->
    <!-- Сайт готов работать с мобильными устройствами -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Загружаем фав-иконки -->
    <link rel="icon" href="{% static 'img/fav/fav.ico' %}" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/fav/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/fav/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/fav/favicon-16x16.png' %}">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <title> {% block title %} {% endblock %} </title> 
  </head>
  <body>
    {% include 'includes/header.html' %}
    <main>
      {% block content %}
            <!-- Содержимое страницы -->
      {% endblock %}
    </main>       
      {% include 'includes/footer.html' %}
  </body>
</html>

yatube/templates/includes/footer.html
<footer class="border-top text-center py-3">
    <p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p>    
  </footer> 

yatube/templates/includes/header.html
{% load static %}
<nav class="navbar navbar-light" style="background-color: lightskyblue">
  <div class="container">
    <a class="navbar-brand" href="{% url 'posts:index' %}">
      <img src="{% static 'img/logo.png' %}" width="30" height="30" 
           class="d-inline-block align-top" alt="">
      <span style="color:red">Ya</span>tube</a>
    </a>
    {% with request.resolver_match.view_name as view_name %}
    <ul class="nav nav-pills">
      <li class="nav-item"> 
        <a class="nav-link{% if view_name  == 'about:author' %} active{% endif %}" 
           href="{% url 'about:author' %}">Об авторе</a>
      </li>
      <li class="nav-item">
        <a class="nav-link{% if view_name  == 'about:tech' %} active{% endif %}" 
           href="{% url 'about:tech' %}">Технологии</a>
      </li>
      {% if user.is_authenticated %}
        <li class="nav-item"> 
          <a class="nav-link{% if view_name  == 'posts:post_create' %} active{% endif %}" 
             href="{% url 'posts:post_create' %}">Новая запись</a>
        </li>
        <li class="nav-item"> 
          <a class="nav-link link-light{% if view_name  == 'password_change' %} active{% endif %}"
             href="{% url 'password_change' %}">Изменить пароль</a>
        </li>
        <li class="nav-item"> 
          <a class="nav-link link-light" href="{% url 'users:logout' %}">Выйти</a>
        </li>
        <li>
          Пользователь: {{ user.username }}
        <li>
      {% else %}
        <li class="nav-item"> 
          <a class="nav-link link-light{% if view_name  == 'users:login' %} active{% endif %}" 
             href="{% url 'users:login' %}">Войти</a>
        </li>
        <li class="nav-item"> 
          <a class="nav-link link-light{% if view_name  == 'users:signup' %} active{% endif %}"
             href="{% url 'users:signup' %}">Регистрация</a>
        </li>
      {% endif %}
    </ul>
    {% endwith %}
  </div>
</nav>

yatube/templates/posts/group_list.html
{% extends "base.html" %}
{% block title %}{{ group.title }}{% endblock %}
{% block content %}
  <h1>{{ group.title }}</h1>
  <p>{{ group.description }}</p>
  {% for post in page_obj %}
    {% include 'posts/includes/article.html' with without_group_links=True %}
    {% if not forloop.last %}
      <hr>
    {% endif %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/includes/article.html
<article>
  <div class="list-group">
    <li class="list-group-item">
      {% if not profile %}
          Автор :
        <a href="{% url 'posts:profile' post.author %}" class="list-group-item-action">
          {{ post.author.get_full_name }} 
        </a>
      {% endif %}
      <br>
      Дата публикации: {{ post.pub_date|date:"d E Y" }}
      <br>
      {% if not without_group_links and post.group %}
        Группа: <a href="{% url 'posts:group_list' post.group.slug %}" class="list-group-item-action">{{ post.group.title }}</a> 
      {% endif %}
      <hr>
      <p>
        {{ post.text|linebreaksbr|truncatechars:500 }}
        <a href="{% url 'posts:post_detail' post.id %}" class="list-group-item-action">подробная информация </a> 
      </p>
    </li>
  </div>
</article>

yatube/templates/posts/includes/paginator.html
{% if page_obj.has_other_pages %}
<nav aria-label="Page navigation" class="my-5">
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
          Предыдущая
        </a>
      </li>
    {% endif %}
    {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
          Следующая
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
          Последняя
        </a>
      </li>
    {% endif %}    
  </ul>
</nav>
{% endif %}

yatube/templates/posts/index.html
{% extends "base.html" %}
{% block title %}Последние обновления на сайте{% endblock %}
{% block content %}
  <h1>Это главная страница проекта Yatube</h1>
    <hr>
    {% for post in page_obj %}
      {% include 'posts/includes/article.html' %}
      {% if not forloop.last %}
        <hr>
      {% endif %}
    {% empty %}
      <p>Нет Постов</p>
    {% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/post_create.html
{% extends 'base.html' %}
{% block title %}{% if is_edit %}Редактировать запись{% else %}Добавить запись{% endif %}{% endblock %}
{% block content %}
<div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">       
            {% if is_edit %}Редактировать запись{% else %}Добавить запись{% endif %}             
          </div>
          <div class="card-body">
              
            {% if form.errors %}
                {% for field in form %}
                {% for error in field.errors %}            
                    <div class="alert alert-danger">
                    {{ error|escape }}
                    </div>
                {% endfor %}
                {% endfor %}
                {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                    {{ error|escape }}
                </div>
                {% endfor %}
            {% endif %}

            <form method="post" enctype="multipart/form-data">
              {% csrf_token %}
             
              {% for field in form %}
              <div class="form-group row my-3 p-3">
                <label for="{{ field.id_for_label }}">
                  {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
                </label>    
                {{ field }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
              {% endfor %}

              <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-primary">
                  {% if is_edit %}
                    Сохранить
                  {% else %}
                    Добавить
                  {% endif %}
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
</div>
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}Пост {{ post_title }}{%endblock%}
{% block content%}
  <main>
    <div class="row">
      <aside class="col-12 col-md-3">
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
            Дата публикации: {{ pub_date|date:"d E Y"}}
          </li>
          {% if post.group %}
          <li class="list-group-item">
            Группа: {{ post.group.title }}
            <a href="{% url 'posts:group_list' post.group.slug %}">
              все записи группы
            </a>
          {% endif %}  
          </li>
          <li class="list-group-item">
            Автор: {{ post.author.get_full_name }}
          </li>
          <li class="list-group-item d-flex justify-content-between align-items-center">
            Всего постов автора:  <span >{{ author_posts }}</span>
          </li>
          <li class="list-group-item">
            <a href="{% url 'posts:profile' post.author %}">
              все посты пользователя
            </a>
          </li>
        </ul>
      </aside>
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <article class="col-12 col-md-9">
        <p>{{ post.text }}</p>
      </article>
    </div>
    {% include 'posts/includes/paginator.html' %}
  </main>
{% endblock %}

yatube/templates/posts/profile.html
{% extends "base.html" %}
{% block content %}
{% block title %}Профиль{% endblock %}
  <h2>Профиль пользователя {{ author.get_full_name}}</h2>
  <h2>Всего постов: {{ author.posts.count }}</h2>
  <hr>
  {% for post in page_obj %}
    {% include 'posts/includes/article.html' with profile=True %}
    {% if not forloop.last %}
      <hr>
    {% endif %}
    {% empty %}
      <p>Нет Постов</p>
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/users/logged_out.html
{% extends "base.html" %}
{% block content%}
    <main>
      <div class="container py-5"> 
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">Выход</div>
              <div class="card-body"> <p>Вы вышли из своей учётной записи. Ждём вас снова!</p>
              </div> <!-- card body -->
            </div> <!-- card -->
          </div> <!-- col -->
        </div> <!-- row --> 
      </div>
      {% include 'posts/includes/paginator.html' %}
    </main>
{% endblock %}

yatube/templates/users/login.html
{% extends "base.html" %}
{% block title %}Войти{% endblock %}
{% block content %}
{% load user_filters %}
  <body>
    <main>
      <div class="container py-5"> 
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                Войти на сайт
              </div>
              <div class="card-body">
                {% if form.errors %}
                {% for field in form %}
                  {% for error in field.errors %}            
                    <div class="alert alert-danger">
                      {{ error|escape }}
                    </div>
                  {% endfor %}
                {% endfor %}
                {% for error in form.non_field_errors %}
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endif %}
                <form method="post" action="{% url 'users:login' %}">
                  {% csrf_token %}    
                  <div class="form-group row my-3">
                    <label for="id_username">
                      Имя пользователя
                      <span class="required text-danger">*</span>
                    </label>
                    <input type="text" name="username" autofocus class="form-control" required id="id_username">
                  </div>
                  <div class="form-group row my-3">
                    <label for="id_password">
                      Пароль
                      <span class="required text-danger">*</span>
                    </label>
                    <input type="password" name="password" class="form-control" required id="id_password">
                  </div>
                  <div class="col-md-6 offset-md-4">
                    <button type="submit" class="btn btn-primary">
                      Войти
                    </button>
                    <a href="{% url 'users:password_reset' %}" class="btn btn-link">
                      Забыли пароль?
                    </a>
                  </div>
                </form>
              </div> 
            </div> 
          </div>
        </div>
      </div>
    </main>
  </body>
</html>
{% endblock %}

yatube/templates/users/password_change_done.html
{% extends "base.html" %}
{% block title %}Пароль изменён{% endblock %}
{% block content %}
  <body>
    <main>
      <div class="container py-5"> 
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                Пароль изменён
              </div>
              <div class="card-body"> 
                <p>Пароль изменён успешно</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </main>
  </body>
</html>
{% endblock %}

yatube/templates/users/password_change_form.html
{% extends "base.html" %}
{% block title %}Новый пароль{% endblock %}
{% block content %}
{% load user_filters %}
<div class="container py-5"> 
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Изменить пароль
        </div>
        <div class="card-body">
          {% if form.errors %}
          {% for field in form %}
            {% for error in field.errors %}            
              <div class="alert alert-danger">
                {{ error|escape }}
              </div>
            {% endfor %}
          {% endfor %}
          {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
              {{ error|escape }}
            </div>
          {% endfor %}
        {% endif %}
          <form method="post" action="{% url 'users:password_change' %}">
            {% csrf_token %} 
            <div class="form-group row my-3 p-3">
              <label for="id_old_password">
                Старый пароль
                <span class="required text-danger">*</span>
              </label>    
              {{ form.old_password }}
            </div>
            <div class="form-group row my-3 p-3">
              <label for="id_new_password1">
                Новый пароль
                <span class="required text-danger">*</span>
              </label>    
              {{ form.new_password1 }}
                <small id="id_new_password1-help" class="form-text text-muted">
                  <ul><li>Ваш пароль не должен совпадать с вашим именем или другой персональной информацией или быть слишком похожим на неё.</li><li>Ваш пароль должен содержать как минимум 8 символов.</li><li>Ваш пароль не может быть одним из широко распространённых паролей.</li><li>Ваш пароль не может состоять только из цифр.</li></ul>
                </small>
            </div>
            <div class="form-group row my-3 p-3">
              <label for="id_new_password2">
                Подтверждение нового пароля
                <span class="required text-danger">*</span>
              </label>    
              {{ form.new_password2 }}
            </div>
            <div class="col-md-6 offset-md-4">
              <button type="submit" class="btn btn-primary">
                Изменить пароль
              </button>
            </div>
          </form>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
  </div> <!-- row -->
</div>
{% endblock %}

yatube/templates/users/password_reset_complete.html
{% extends "base.html" %}
{% block title %}Пароль сброшен{% endblock %}
{% block content %}
  <body>
    <main>
      <div class="container py-5"> 
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                Восстановление пароля завершено
              </div>
              <div class="card-body">
                <p>Ваш пароль был сохранен. Используйте его для входа</p>
                <a href="{% url 'users:login' %}">войти</a>
              </div> 
            </div> 
          </div>
        </div> 
      </div>
    </main>
  </body>
</html>
{% endblock %}

yatube/templates/users/password_reset_confirm.html
{% extends "base.html" %}
{% block title %}Новый пароль{% endblock %}
{% block content %}
{% if validlink %}
    <main>
      <div class="container py-5"> 
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                Введите новый пароль
              </div>
              <div class="card-body">
                <form method="post" action="">
                  {% csrf_token %}
                  <div class="form-group row my-3 p-3">
                    <label for="id_new_password1">
                      Новый пароль        
                      <span class="required text-danger">*</span>        
                    </label>    
                    <input type="password" name="new_password1" class="form-control" required id="id_new_password1">      
                    <small id="id_new_password1-help" class="form-text text-muted">
                      <ul><li>Ваш пароль не должен совпадать с вашим именем или другой персональной информацией или быть слишком похожим на неё.</li><li>Ваш пароль должен содержать как минимум 8 символов.</li><li>Ваш пароль не может быть одним из широко распространённых паролей.</li><li>Ваш пароль не может состоять только из цифр.</li></ul>
                    </small>      
                  </div>
                  <div class="form-group row my-3 p-3">
                    <label for="id_new_password2">
                      Подтверждение нового пароля        
                      <span class="required text-danger">*</span>        
                    </label>    
                    <input type="password" name="new_password2" class="form-control" required id="id_new_password2">      
                  </div>
                  <div class="col-md-6 offset-md-4">
                    <button type="submit" class="btn btn-primary">
                      Назначить новый пароль
                    </button>
                  </div>
                </form>
              </div> <!-- card body -->
            </div> <!-- card -->
          </div> <!-- col -->
        </div> <!-- row -->
        {% else %}
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                Ошибка
              </div>
              <div class="card-body">
                <p>Ссылка сброса пароля содержит ошибку или устарела.</p>
              </div> <!-- card body -->
            </div> <!-- card -->
          </div> <!-- col -->
        </div> <!-- row -->
        {% endif %}
      </div>
    </main>
  </body>
</html>
{% endblock %}

yatube/templates/users/signup.html
{% extends "base.html" %}
{% block title %}Зарегистрироваться{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Зарегистрироваться</div>
          <div class="card-body">
          {% load user_filters %} {# Загружаем фильтры #}
              {% if form.errors %}
                  {% for field in form %} 
                    {% for error in field.errors %}            
                      <div class="alert alert-danger">
                        {{ error|escape }}
                      </div>
                    {% endfor %}
                  {% endfor %}
                  {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                      {{ error|escape }}
                    </div>
                  {% endfor %}
              {% endif %}

              <form method="post" action="{% url 'users:signup' %}">
              {% csrf_token %}

              {# Выводим поля в цикле, по отдельности #}
              {% for field in form %} 
                <div class="form-group row my-3">
                  <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                      {% if field.field.required %}
                        <span class="required text-danger">*</span>
                      {% endif %}
                  </label>
                  {# К полю ввода добавляем атрибут class #}
                  {{ field|addclass:'form-control' }} 
                    {% if field.help_text %}
                      <small 
                         id="{{ field.id_for_label }}-help"
                         class="form-text text-muted"
                      >
                        {{ field.help_text|safe }}
                      </small>
                    {% endif %}
                </div>
              {% endfor %}
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  Зарегистрироваться
                </button>
              </div>
            </form>
          </div> <!-- card body -->
        </div> <!-- card -->
      </div> <!-- col -->
  </div> <!-- row -->
{% endblock %}